export const string1 = `
https://www.aau.dk/
https://www.aau.dk/3-nye-tiltag-i-kantinen-der-gavner-bade-su-budgettet-og-klimaet-n43866
https://www.aau.dk/uden-mad-og-drikke-duer-helten-ikke-n94515
https://www.aau.dk/nyt-aau-kantineudbud-har-oget-fokus-pa-okologi-og-baeredygtig-drift-n5941
https://vbn.aau.dk/da/projects/udvikling-af-en-membranproces-til-raffinering-af-h%C3%B8jkvalitets-f%C3%B8d
https://www.bio.aau.dk/baer-og-frugtavl-skal-tilpasses-klimaforandringerne-n19023
https://www.bio.aau.dk/edible-insects-for-a-sustainable-future-e28489
https://www.aau.dk/naturmodet-2022-e19972
https://www.en.aau.dk/cooperation/laboratories-equipment
https://www.bio.aau.dk/forskning/forskningsomrader/sustainable-bioresource-technology#facilities
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/0pvlyxhi/aalborg-universitets-strategiske-rammekontrakt-2022-2025.pdf
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/o2zb0clm/uld-strategi-040122-uk.pdf
https://www.aau.dk/samarbejde/tilbud-til-gymnasier/aau-play
https://www.aau.dk/samarbejde/tilbud-til-gymnasier/on-demand
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/yijmkktv/1154338_akutmedicin.pdf
https://www.aau.dk/uddannelser/efteruddannelse/enkeltfag-kurser
https://www.kultur.aau.dk/public-seminar-on-antiracist-education-e44032
https://www.naturvidenskabsfestivalaalborg.dk/
https://www.en.aub.aau.dk/meet-us/public-access
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/ky1dqtag/statistik-energiforbrug-2006-2022.pdf
https://www.aau.dk/regn-og-spildevand-n94521
https://www.sikkerkemi.aau.dk/kemisk-arbejdsmiljo/kemikalieaffald#opsamling-af-kemisk-affald
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/todlx5et/studiemilj%C3%B8-%C3%A5rsrapport-2022.pdf
https://www.campusservice.aau.dk/praktiske-oplysninger/til-eksterne-samarbejdspartnere
https://www.aau.dk/ny-adal-pa-campus-i-aalborg-n11164
https://www.aau.dk/aau-som-living-lab-taeller-insekter-og-planter-traeer-n94524
https://www.en.build.aau.dk/lab/ocean-and-coastal-engineering
https://www.aau.dk/samarbejde/tilbud-til-gymnasier/aau-play/baeredygtighed/hvordan-sikrer-vi-at-vi-har-rent-vand-og-nok-ressourcer-i-fremtiden
https://www.aau.dk/aau-skaber-gronne-rammer-om-et-baeredygtigt-studieliv-n6831
https://www.dat.aau.dk/forskning/ai-ml-artificial-intelligence-and-machine-learning/projekter/claire
https://www.en.build.aau.dk/research/urban-water
https://www.kultur.aau.dk/vidensamarbejde/teknologi-alene-loser-ikke-den-digitale-omstilling-af-vandbranchen
https://vbn.aau.dk/en/projects/water-resources-system-safe-operating-space-in-a-changing-climate
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/qdyflbma/teknisk-kravspecifikation-maj-2023.pdf
https://www.en.aau.dk/education/apply/master/how-and-when-to-apply#how-to-apply
https://www.staff.aau.dk/rules/education/admission-and-enrolment-to-full-time-study-programmes-at-aalborg-university
https://www.en.aau.dk/about-aau/key-figures/students/gender-distribution
https://www.ansatte.aau.dk/inkluderende-rekruttering-n61537
https://www.kvalitet.aau.dk/strategiske-uddannelsesdata/
https://www.students.aau.dk/student-life/inclusion-at-aau#choice-of-study
https://www.staff.aau.dk/rules/staff-affairs/offensive-behaviour#general
https://www.staff.aau.dk/rules/staff-affairs/offensive-behaviour-procedure
https://www.staff.aau.dk/organisation/committees/committee-for-equality-and-diversity
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/hlvl0end/uld-strategi-040122-resume-uk.pdf
https://www.staff.aau.dk/aau-s-mentoring-program-brings-staff-together-across-aau-for-career-development-conversations-n64529
https://www.students.aau.dk/choices-along-the-way-and-jobs/gain-experience-while-you-study/buddy#what-is-the-buddy-programme
https://clients.mapsindoors.com/aau/57482221bc1f570e288b8ef0/search?cat=handicap%20entrance
https://www.students.aau.dk/student-life/sps
https://www.ansatte.aau.dk/regler/personaleforhold/personlig-assistance-handicapledsagere-i-staten#ans%C3%A6ttelse-af-personlige-assistenter
https://www.students.aau.dk/student-life/sps/hearing-or-visual#6a1b7cec-b678-407a-a901-2fa7cd0f20c2
https://vbn.aau.dk/da/activities/hav-og-klima-havets-rolle-i-kampen-mod-klimaforandringerne
https://www.bio.aau.dk/havforsker/program
https://vbn.aau.dk/da/projects/constraints-and-trade-offs-in-the-climate-impact-of-fisheries
https://www.bio.aau.dk/havforsker
https://www.ansatte.aau.dk/regler/personaleforhold/mad-og-maltidspolitik#m%C3%A5ls%C3%A6tninger-for-m%C3%A5ltider-p%C3%A5-aalborg-universitet
https://www.bio.aau.dk/for-100-mio-naturgenopretning-til-gavn-for-marin-natur-miljo-og-klima-n50889
https://www.aau.dk/kunstig-intelligens-skal-indsamle-mere-og-bedre-maritimt-data-til-at-forsta-miljoproblemer-n13944
https://www.sikkerkemi.aau.dk/kemikalieaffald#spildevandstilladelser-p%C3%A5-aau
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/kduabgxr/aau_klimaplan-da.pdf
https://www.sikkerkemi.aau.dk/kemisk-arbejdsmiljo/kemikalieaffald#spildevandstilladelser-p%C3%A5-aau
https://vbn.aau.dk/en/organisations/centre-for-blue-governance#:~:text=The%20Centre%20for%20Blue%20Governance,between%20people%20and%20the%20sea
https://bygst.dk/nyheder/2020/juli/aalborg-universitet-klimasikres-mod-kraftige-skybrud/
https://www.students.aau.dk/guidance/su-guidance#
https://www.studieservice.aau.dk/trivselsportal
https://www.studerende.aau.dk/studieliv/trivsels-og-stottetilbud-til-dig
https://www.studerende.aau.dk/vejledning
https://www.en.aau.dk/education/apply/master/finance-and-fees#scholarships---only-for-master's-programmes
https://www.aau.dk/nyt-dansk-initiativ-skal-hjaelpe-ukrainske-forskere-paa-flugt-n36600
https://www.se.aau.dk/students/incubators/
https://www.innovate.aau.dk/lets-innovate/garager/ansog-om-garage
https://www.students.aau.dk/choices-along-the-way-and-jobs/entrepreneurship-and-innovation/aau-startup-program/aau-startup-grant
https://www.students.aau.dk/choices-along-the-way-and-jobs/entrepreneurship-and-innovation/aau-startup-program/aau-startup-grant/former-winners-of-the-aau-startup-grant/biomend
https://www.hst.aau.dk/research#increasing-public-health-in-our-society
https://www.kommunikation.aau.dk/green-charcoal-shall-enable-sustainable-cooking-in-uganda-n43156
https://vbn.aau.dk/da/activities/b%C3%B8rnefattigdom-i-et-velf%C3%A6rdssamfund-og-i-gentofte
https://www.predictibd.dk/
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/atrjszyd/program-fo-hertoft-eftermiddage-2021-2022.pdf
https://www.kommunikation.aau.dk/forskning/forskningsklynger/ahh/forskning/moving-together
https://www.aau.dk/indvielse-i-gigantium-nu-flytter-aau-s-idraetsuddannelser-ind-n27257
https://www.aau.dk/samarbejde/tilbud-til-gymnasier/on-demand/oplaeg/sund/sund-aal/klinisk/let-s-talk-about-sex-baby
https://www.staff.aau.dk/rules/staff-affairs/psychological-counselling-service#offer-to-all-staff-members-for-psychological-counselling-with-dansk-erhvervspsykologi
https://www.studerende.aau.dk/vejledning/studie-trivselsvejledning
https://www.staff.aau.dk/rules/staff-affairs/smoke-free-workplace-policy#content
https://www.kvalitet.aau.dk/digitalAssets/1279/1279170_strategiske-uddannelsesdata---for-aau-og-sektoren-november-2022.pdf
https://www.studerende.aau.dk/studieliv/inklusion-pa-aau#studievalg
https://www.aau.dk/rekordstor-interesse-for-girls-day-in-science-pa-aau-n44830
https://www.students.aau.dk/student-life/inclusion-at-aau#inclusive-study-environments
https://www.staff.aau.dk/rules/staff-affairs/offensive-behaviour#what-is-offensive-behaviour?
https://www.aau.dk/rector-there-are-too-few-women-in-aau-s-senior-management-n72432
https://www.staff.aau.dk/organisation/committees/committee-for-equality-and-diversity/more-information-about-equality-and-diversity#preventing-discrimination-against-transgender-persons
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/x2imllvb/handleplan-for-ligestilling-og-diversitet-ift-studerende-september-2023.pdf
https://www.staff.aau.dk/rules/staff-affairs/parental-leave#2.-maternity-leave-(week-1-10
https://www.students.aau.dk/rules/taking-a-break/pregnancy-and-parental-absence
https://www.isu.aau.dk/upon-arrival/learning-danish/#368117
https://www.isu.aau.dk/upon-arrival/learning-danish/#368118
https://www.en.aub.aau.dk/meet-us/branches-and-opening-hours/bring-the-kids
https://www.ansatte.aau.dk/aau-s-mentorprogram-bringer-medarbejdere-sammen-pa-tvaers-af-aau-til-samtaler-om-karriereudvikling-n61475
https://www.staff.aau.dk/rules/staff-affairs/offensive-behaviour-procedure#how-aalborg-university-handles-cases-of-possible-offensive-behaviour
`

export const string2 = `
https://www.en.aau.dk/about-aau/contact/whistleblowing-scheme#can-you-remain-anonymous?
https://www.aau.dk/nye-baeredygtighedskrav-til-byggeri-pa-aalborg-universitet-n45474
https://www.aau.dk/campus-service-arbejder-malrettet-pa-at-spare-pa-energiforbruget-n45213
https://www.aau.dk/om-aau/profil/baeredygtighed#klimam%C3%A5l-for-aau
https://www.en.campusservice.aau.dk/sustainable-campus/energy-optimization
https://www.energiledelse.aau.dk/energimaerkning/
https://www.aau.dk/om-aau/organisation/investeringspolitik
https://www.energy.aau.dk/globalt-forskningsprojekt-fremtidens-lokalsamfund-leverer-selv-gron-energi-n25854
https://www.energy.aau.dk/2022-05-23-exhibition-in-the-danish-museum-of-energy-with-help-from-aau-energy-n30388
https://vbn.aau.dk/da/projects/varmeplan-danmark-2021-en-klimaneutral-varmeforsyning
https://www.aau.dk/esbjerg-samler-folk-og-energiaktorer-om-en-gron-fremtid-n41405
https://vbn.aau.dk/da/projects/medium-voltage-power-electronics-for-wind-systems
https://vbn.aau.dk/en/publications/repowereu-and-fitfor55-science-based-policy-recommendations-for-a
https://www.engineering.aau.dk/erhvervs-ph-d-fra-aalborg-universitet-har-planlagt-faeroernes-gronne-omstilling-n53605
https://www.students.aau.dk/choices-along-the-way-and-jobs/entrepreneurship-and-innovation/aau-startup-program
https://www.innovate.aau.dk/lets-innovate/garager/garage-06
https://www.ansatte.aau.dk/regler/personaleforhold/lonpolitik-tap#3.-l%C3%B8nafs%C3%A6ttelse-og--forhandlingsprocedure
https://www.hr.aau.dk/lon/loenoversigter/
https://www.ansatte.aau.dk/regler/personaleforhold/frit-organisationsvalg
https://www.studerende.aau.dk/valg-undervejs-og-job/snart-nyuddannet/fagforeninger
https://www.staff.aau.dk/rules/staff-affairs/equality-and-diversity
https://www.staff.aau.dk/rules/staff-affairs/offensive-behaviour#what-is-offensive-behaviour
https://www.staff.aau.dk/rules/staff-affairs/code-of-conduct
https://www.staff.aau.dk/rules/finances/procurement-and-supply-policy-for-aalborg-university#overall-purpose-of-the-policy
https://www.staff.aau.dk/organisation/committees/committee-for-equality-and-diversity/more-information-about-equality-and-diversity#equality-and-equal-pay
https://www.ansatte.aau.dk/regler/personaleforhold/tillidshverv-og-tillidsrepraesentanter#funktionsbeskrivelser
https://prod-aaudxp-cms-001-app.azurewebsites.net/media/4grn0fn3/naturfagsdagen2022.pdf
https://www.aau.dk/samarbejde/tilbud-til-gymnasier/aau-play/baeredygtighed/kan-vi-tillade-os-at-bruge-endnu-en-mark-til-byudvikling
https://www.aau.dk/samarbejde/tilbud-til-gymnasier/on-demand/oplaeg/eng/eng-aal/kemi-og-biovidenskab/invasive-arter-nar-gaesterne-bliver-boende
https://www.en.aau.dk/aau-as-a-living-lab-counting-insects-and-plants-trees-n94525
https://www.aau.dk/vild-med-vilje-fejrer-4-ars-fodselsdag-pa-aau-n43473
https://www.en.aau.dk/rain-and-wastewater-n94522
https://www.sikkerkemi.aau.dk/kemisk-arbejdsmiljo/kemikalieaffald#klinisk-risikoaffald
https://www.staff.aau.dk/rules/organization/statutes-for-aalborg-university#the-university-board
https://www.staff.aau.dk/rules/education/election-rules#chapter-1---governing-bodies-and-their-composition
https://www.staff.aau.dk/rules/students/code-of-practice-for-cooperation-between-the-university-and-its-students#aau-invites-to-a-democratic-and-open-dialogue
https://www.aau.dk/ny-funktion-i-aau-connect-appen-gor-det-endnu-lettere-for-virksomheder-at-samarbejde-med-aau-n15128
https://www.en.aau.dk/about-aau/strategy
https://www.kvalitet.aau.dk/digitalAssets/991/991083_6.2.1-procedure-for-neds--ttelse-af-og-dialog-med-aftagerpaneler.pdf
https://www.aau.dk/om-aau/organisation/ledelse/bestyrelse#claus-kim-holstein
https://www.staff.aau.dk/rules/organization/statutes-for-aalborg-university#objective-
https://www.okonomi.aau.dk/digitalAssets/1294/1294820_endelig-version-af---r2022--lagt-p---hjemmesiden---d3437910-.pdf
https://www.en.aau.dk/about-aau/key-figures/finances
https://www.law.aau.dk/birgit-feldtmann-udpeget-som-aaus-repraesentant-i-bestyrelsen-for-institut-for-menneskerettigheder-n76225
https://www.en.soc.aau.dk/research/research-groups/scopas/news/news-item/medlem-af-raadgivende-organ-for-videnscenter-for-videnscenter-om-boerneinddragelse-og-udsatte-boerns-liv.cid539973
https://www.aau.dk/uddannelser/efteruddannelse/master/master-i-offentlig-ledelse
https://www.aau.dk/juridisk-institut-pa-aau-star-bag-landets-storste-jurakonference-n33910
https://www.en.plan.aau.dk/research/sustainability-innovation-policy
https://www.staff.aau.dk/rules/organization/rules-for-staff-members-freedom-of-speech#content
https://www.aau.dk/debat-med-statsminister-mette-frederiksen-om-udenrigs-og-sikkerhedspolitik-e15516
https://www.aau.dk/nyt-samarbejde-mellem-aalborg-universitet-og-hjorring-kommune-skal-lofte-ungegarantien-n80861
https://www.aau.dk/retsvidenskabelig-forskning-og-ny-viden-fra-aau-understotter-udmontningen-af-fn-s-verdensmal-n6787
https://www.aau.dk/new-scheme-for-waste-separation-at-aau-n13348
https://www.studerende.aau.dk/studieliv/indflydelse-studiemiljoe/baeredygtigt-studieliv
https://www.campusservice.aau.dk/aau-inde-og-ude/adgangskontrol
https://www.aub.aau.dk/mod-os/brug-biblioteket-dognet-rundt/laneregler
https://www.ansatte.aau.dk/tilbud/skraningen
https://www.en.campusservice.aau.dk/campus-service-cph/art-on-campus
https://www.en.campusservice.aau.dk/aau-inside-and-outside/green-breathing-spaces
https://www.kajmunk.aau.dk/
https://www.aau.dk/aau-laegger-plan-for-mere-baeredygtig-mobilitet-n94526
https://www.aau.dk/commute-to-aau-in-a-climate-conscious-way-n13343
https://www.aau.dk/aau-pendler-hop-med-pa-vognen-og-find-en-koerselsmakker-n33893
https://www.ansatte.aau.dk/regler/personaleforhold/distancearbejde-aau-faelles-service#form%C3%A5l-og-afgr%C3%A6nsning
https://www.update.aau.dk/universitetsdirektoer-faelles-principper-for-distancearbejde-med-plads-til-forskellighed-n26270
https://www.en.aau.dk/living-in-denmark/accommodation/international-students-in-aalborg
https://www.en.aau.dk/living-in-denmark/accommodation/phd-and-staff-in-aalborg
https://www.en.aau.dk/living-in-denmark/accommodation/phd-and-staff-in-copenhagen
https://www.aau.dk/kom-klimabevidst-til-aau-n6078
https://www.arbejdsmiljoe.aau.dk/Walk+%26+Talk+forside+/
https://www.aau.dk/aau-investerer-i-gron-strom-fra-danske-vindmoller-n6694
https://www.aau.dk/aau-sparer-pa-energien-og-far-en-storre-andel-fra-baeredygtige-energikilder-n6723
https://www.aau.dk/folkeuniversitetet-byder-velkommen-til-et-foraar-i-klimaets-tegn-n22545
https://www.aau.dk/uddannelser/efteruddannelse/enkeltfag-kurser/livscyklusvurdering-lca-med-fokus-pa-klimaaftryk
https://www.aau.dk/invitation-to-the-final-flow-conference-e10606
https://www.kultur.aau.dk/indtryk-fra-klimatopmode-i-lemvig-n41037
https://www.aau.dk/the-european-law-institute-eli-evaluates-and-stimulates-the-development-of-law-legal-policy-and-practice-for-the-benefit-of-european-legal-and-natural-citizens-n61161
https://www.plan.aau.dk/forskning/dansk-center-for-miljovurdering-dcea#1b609d15-d613-4f82-a8e0-c5f77063925d
https://www.en.plan.aau.dk/research/the-danish-centre-for-environmental-assessment/getting-the-data-right#e2bc48f9-08a2-4968-9231-7738f0582b46
https://www.energy.aau.dk/new-consortium-to-commercialise-the-production-of-sustainable-fuels-for-aircraft-and-ships-n45945
https://www.aau.dk/uddannelser/baeredygtighed#6d640869-7589-441f-b0f2-1ed9e8a89607
https://www.megaprojects.aau.dk/Megaproject+Blue+Denmark/
https://www.aau.dk/om-aau/profil/pbl
https://old.sparenergi.dk/offentlig/vaerktoejer/offentligt-energiforbrug/aalborg-universitet
https://aalborgkommune.viewer.dkplan.niras.dk/plan/33#/
https://cleancluster.dk/tilbud/temadag-rensning-af-overfladevand-klimatilpasning-og-bat/
https://aalborgforsyning.dk/privat/gronne-losninger/drikkevand/
https://mitvand.dk/saadan-er-du-forsynet/1
https://www.face-it-project.eu/2022/06/15/face-it-scenario-workshop-in-nuuk-greenland/
https://dakofa.dk/element/plastikforurening-hvad-er-problemerne-og-hvordan-kan-vi-minimere-dem/
https://www.pdjf.dk/programmer/cirkulaer-fosforgenindvinding-repair/
https://www.engineering.aau.dk/forskning/udvalgte-forskningsprojekter/aau-udvikler-losninger-pa-plastikforureningen-i-havet
https://aalborgforsyning.dk/privat/gronne-losninger/spildevand/grava/
https://www.aalborgretshjaelp.dk/
https://www.labwelfaretech.com/en/fp/af/
https://biffen.eu/events/den-sexologiske-filmkanon/
https://via.ritzau.dk/pressemeddelelse/13656439/forskere-fra-hele-verden-er-enige-mal-om-100-procent-vedvarende-energi-i-verden-inden-2050-er-realistisk?publisherId=8155951
https://www.hlrn.org/activitydetails.php?title=Land-Governance-Is-Key-to-Implement-2030-Agenda&id=p21taw==
https://musikkenshus.dk/kalender/event-arkiv/2022/demenskor
https://aftenskole.nu/Aalborg/Hold/Aalborg-Universitets-Big-Band
https://www.abhim.dk/seneste-nyt/nyhedsarkiv/nyheder-2022/endelig-gang-i-renoveringsprojekt-ved-aau-campus
https://www.aalborg.dk/om-kommunen/udvikling-og-planer/udvikling-af-kommunen/gigantiumkvarteret
https://www.c2ccc.eu/english/about/
https://klimaraadet.dk/en/heiselberg
https://klimatorium.dk/universitetsstuderende-hoester-viden-i-vestjylland/
https://www.dnnk.dk/om-dnnk/
https://www.co2vision.dk/om-os/
https://smartenergysystems.eu/2022-2/
https://www.globalfocusmagazine.com/aaubs-collaborates-with-international-organisations-to-solve-global-challenges-through-data-science/
https://ewh-aau.dk/
https://nben.dk/ydelser/projekter/det-gronne-rejsehold
https://www.youthsgogreen.dk/om-projektet/`
